const PDFDocument = require('pdfkit');
const nodemailer = require('nodemailer');

const generateInvoicePDF = (invoice, user) => {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ margin: 50, size: 'A4' });
      const chunks = [];
      doc.on('data', chunk => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      const blue = '#2563eb';
      const lightGray = '#f8fafc';
      const darkText = '#1e293b';
      const mutedText = '#64748b';

      // Header bar
      doc.rect(0, 0, doc.page.width, 80).fill(blue);
      doc.fillColor('#ffffff').fontSize(28).font('Helvetica-Bold').text('INVOICE', 50, 25);
      doc.fontSize(10).font('Helvetica').text(user.name, 50, 58);

      // Invoice meta (top right)
      doc.fillColor('#ffffff').fontSize(10)
        .text(`Invoice #: ${invoice.invoiceNumber}`, 350, 25, { width: 200, align: 'right' })
        .text(`Date: ${new Date(invoice.createdAt).toLocaleDateString()}`, 350, 40, { width: 200, align: 'right' })
        .text(`Due: ${new Date(invoice.dueDate).toLocaleDateString()}`, 350, 55, { width: 200, align: 'right' });

      // Bill To section
      doc.fillColor(darkText).fontSize(11).font('Helvetica-Bold').text('BILL TO', 50, 110);
      doc.moveTo(50, 124).lineTo(200, 124).strokeColor(blue).lineWidth(1.5).stroke();
      doc.fillColor(darkText).fontSize(10).font('Helvetica')
        .text(invoice.clientId.name, 50, 130)
        .text(invoice.clientId.company || '', 50, 145)
        .text(invoice.clientId.email, 50, 160);

      // From section
      doc.fillColor(darkText).fontSize(11).font('Helvetica-Bold').text('FROM', 350, 110);
      doc.moveTo(350, 124).lineTo(500, 124).strokeColor(blue).lineWidth(1.5).stroke();
      doc.fillColor(darkText).fontSize(10).font('Helvetica')
        .text(user.name, 350, 130)
        .text(user.email || '', 350, 145)
        .text(user.phone || '', 350, 160);

      // Items table header
      const tableTop = 210;
      doc.rect(50, tableTop, doc.page.width - 100, 24).fill(blue);
      doc.fillColor('#ffffff').fontSize(10).font('Helvetica-Bold')
        .text('Description', 60, tableTop + 7)
        .text('Qty', 320, tableTop + 7, { width: 50, align: 'center' })
        .text('Rate', 375, tableTop + 7, { width: 70, align: 'right' })
        .text('Amount', 450, tableTop + 7, { width: 90, align: 'right' });

      // Items rows
      let y = tableTop + 24;
      invoice.items.forEach((item, i) => {
        const rowBg = i % 2 === 0 ? lightGray : '#ffffff';
        doc.rect(50, y, doc.page.width - 100, 22).fill(rowBg);
        doc.fillColor(darkText).fontSize(10).font('Helvetica')
          .text(item.description, 60, y + 6, { width: 255 })
          .text(String(item.quantity), 320, y + 6, { width: 50, align: 'center' })
          .text(`$${item.rate.toFixed(2)}`, 375, y + 6, { width: 70, align: 'right' })
          .text(`$${item.amount.toFixed(2)}`, 450, y + 6, { width: 90, align: 'right' });
        y += 22;
      });

      // Totals
      y += 16;
      doc.moveTo(350, y).lineTo(540, y).strokeColor('#e2e8f0').lineWidth(1).stroke();
      y += 10;

      const totalsLeft = 350;
      doc.fillColor(mutedText).fontSize(10).font('Helvetica')
        .text('Subtotal:', totalsLeft, y, { width: 100 })
        .text(`$${invoice.subtotal.toFixed(2)}`, totalsLeft + 100, y, { width: 90, align: 'right' });
      y += 18;
      doc.text(`Tax (${invoice.taxPercent}%):`, totalsLeft, y, { width: 100 })
        .text(`$${invoice.taxAmount.toFixed(2)}`, totalsLeft + 100, y, { width: 90, align: 'right' });
      y += 10;
      doc.moveTo(350, y).lineTo(540, y).strokeColor('#e2e8f0').lineWidth(1).stroke();
      y += 10;
      doc.fillColor(blue).fontSize(13).font('Helvetica-Bold')
        .text('Total:', totalsLeft, y, { width: 100 })
        .text(`$${invoice.total.toFixed(2)}`, totalsLeft + 100, y, { width: 90, align: 'right' });

      // Status badge
      const statusColors = { Paid: '#16a34a', Unpaid: '#d97706', Overdue: '#dc2626' };
      const statusBg = statusColors[invoice.status] || '#64748b';
      doc.rect(50, y - 5, 80, 24).fill(statusBg).fillColor('#ffffff')
        .fontSize(10).font('Helvetica-Bold')
        .text(invoice.status, 50, y + 2, { width: 80, align: 'center' });

      // Footer
      const footerY = doc.page.height - 60;
      doc.rect(0, footerY, doc.page.width, 60).fill(lightGray);
      doc.fillColor(mutedText).fontSize(9).font('Helvetica')
        .text('Thank you for your business!', 50, footerY + 12, { align: 'center', width: doc.page.width - 100 })
        .text(`Generated by FreelanceFlow · ${new Date().toLocaleDateString()}`, 50, footerY + 28, { align: 'center', width: doc.page.width - 100 });

      doc.end();
    } catch (err) {
      reject(err);
    }
  });
};

const createTransporter = () => nodemailer.createTransporter({
  host: process.env.EMAIL_HOST,
  port: Number(process.env.EMAIL_PORT) || 587,
  secure: false,
  auth: { user: process.env.EMAIL_USER, pass: process.env.EMAIL_PASS },
  tls: { rejectUnauthorized: false }
});

const sendInvoiceEmail = async (invoice, user) => {
  if (!process.env.EMAIL_USER || !process.env.EMAIL_PASS) {
    throw new Error('Email credentials are not configured in .env');
  }
  const transporter = createTransporter();
  await transporter.verify();
  const pdfBuffer = await generateInvoicePDF(invoice, user);
  await transporter.sendMail({
    from: `"${user.name}" <${process.env.EMAIL_USER}>`,
    to: invoice.clientId.email,
    subject: `Invoice ${invoice.invoiceNumber} from ${user.name}`,
    text: `Please find attached invoice ${invoice.invoiceNumber}.\nDue: ${new Date(invoice.dueDate).toLocaleDateString()}\nTotal: $${invoice.total.toFixed(2)}`,
    html: `<p>Hi ${invoice.clientId.name},</p><p>Please find attached invoice <strong>${invoice.invoiceNumber}</strong> for <strong>$${invoice.total.toFixed(2)}</strong>.</p><p>Due: ${new Date(invoice.dueDate).toLocaleDateString()}</p><p>Thanks,<br/>${user.name}</p>`,
    attachments: [{ filename: `invoice-${invoice.invoiceNumber}.pdf`, content: pdfBuffer }]
  });
};

module.exports = { generateInvoicePDF, sendInvoiceEmail };
